name: CI/CD → Minikube
 
on:
  push:
    branches: [ main ]
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
      # 1) Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3
 
      # 2) Installer Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
 
      # 3) Installer kubectl et minikube
      - name: Install kubectl & Minikube
        run: |
          # kubectl
          curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install kubectl /usr/local/bin/
          # minikube
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
 
      # 4) Démarrer Minikube en mode Docker
      - name: Start Minikube
        run: minikube start --driver=docker
 
      # 5) Se logguer sur Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
      # 6) Build et charger l’image dans Minikube
      - name: Build & load image
        run: |
          docker build -t myflaskapp:latest .
          minikube image load myflaskapp:latest
 
      # 7) Déployer les manifests K8s
      - name: Deploy to Minikube
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/ingress.yaml
          kubectl apply -f k8s/hpa.yaml
          kubectl rollout status deployment/myflaskapp --timeout=120s
 
      # 8) Smoke-test rapide
      - name: Smoke test
        run: |
          kubectl port-forward svc/myflaskapp-service 5000:80 &
          sleep 5
          curl -f http://127.0.0.1:5000/ || exit 1
