apiVersion: apps/v1
kind: Deployment
metadata:
  name: myflaskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myflaskapp
  template:
    metadata:
      labels:
        app: myflaskapp
    spec:
      containers:
        - name: myflaskapp
          image: myflaskapp:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: myflaskapp-config
            - secretRef:
                name: myflaskapp-secret
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /api/events
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/events
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
